//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenEhr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AmValidationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AmValidationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenEhr.Resources.AmValidationStrings", typeof(AmValidationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If ArchetypeInternalRef.TargetPath is not null/empty then the root object must have the target path (ultimate_root.HasPath(Targetpath) must be true)..
        /// </summary>
        internal static string ArchetypeInternalRefTargetPathMissing {
            get {
                return ResourceManager.GetString("ArchetypeInternalRefTargetPathMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation of ArchetypeSlot instances is not yet implemented..
        /// </summary>
        internal static string ArchetypeSlotValidationNotImplemented {
            get {
                return ResourceManager.GetString("ArchetypeSlotValidationNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If archetype is specialised the specialisation depth must be greater than zero..
        /// </summary>
        internal static string ArchetypeSpecialisationInvariantFail {
            get {
                return ResourceManager.GetString("ArchetypeSpecialisationInvariantFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archetype.Version() must be equal to Archetype.ArchetypeId.VersionId.
        /// </summary>
        internal static string ArchetypeVersionNotEqual {
            get {
                return ResourceManager.GetString("ArchetypeVersionNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load operational archetype &apos;{0}&apos; for validation..
        /// </summary>
        internal static string ArchetypeXLoadFailed {
            get {
                return ResourceManager.GetString("ArchetypeXLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assumed value present but that value is not valid against the constraint..
        /// </summary>
        internal static string AssumedValueInvalid {
            get {
                return ResourceManager.GetString("AssumedValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find reference model type corresponding to &apos;{0}&apos;..
        /// </summary>
        internal static string CannotResolveRmTypeName {
            get {
                return ResourceManager.GetString("CannotResolveRmTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardinality must be lower bounded..
        /// </summary>
        internal static string CardinalityLowerUnbounded {
            get {
                return ResourceManager.GetString("CardinalityLowerUnbounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardinality interval lower must be bounded..
        /// </summary>
        internal static string CardinalityMustBeBounded {
            get {
                return ResourceManager.GetString("CardinalityMustBeBounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of items ({0}) for attribute &apos;{1}&apos; is outside the cardinality constraint interval..
        /// </summary>
        internal static string CardinalityOutOfBounds {
            get {
                return ResourceManager.GetString("CardinalityOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either CComplexObject.Attributes is not null and not empty or CComplexObject must allow any attribute..
        /// </summary>
        internal static string CComplexObjectAllowAnyXor {
            get {
                return ResourceManager.GetString("CComplexObjectAllowAnyXor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected first child of name attribute to be a CDefinedObject..
        /// </summary>
        internal static string CDefinedObjectNameChildExpected {
            get {
                return ResourceManager.GetString("CDefinedObjectNameChildExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting terminology ID &apos;{0}&apos; but got &apos;{1}&apos;..
        /// </summary>
        internal static string CodePhraseTerminologyWrong {
            get {
                return ResourceManager.GetString("CodePhraseTerminologyWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected code string &apos;{0}&apos;. Not in codes list..
        /// </summary>
        internal static string CodeStringXNotInList {
            get {
                return ResourceManager.GetString("CodeStringXNotInList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constraint path must not end with forward slash (/): {0}..
        /// </summary>
        internal static string ConstraintPathBadEnding {
            get {
                return ResourceManager.GetString("ConstraintPathBadEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constraint path is malformed: {0}..
        /// </summary>
        internal static string ConstraintPathMalformed {
            get {
                return ResourceManager.GetString("ConstraintPathMalformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.IsValid() must be true..
        /// </summary>
        internal static string ConstraintXIsValidGetsFalse {
            get {
                return ResourceManager.GetString("ConstraintXIsValidGetsFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either CPrimitiveObject.Item is not null or CPrimitiveObject must allow any item..
        /// </summary>
        internal static string CPrimitiveObjectAllowAnyXor {
            get {
                return ResourceManager.GetString("CPrimitiveObjectAllowAnyXor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CReal.AssumedValueSet must be true..
        /// </summary>
        internal static string CRealAssumedValueSetFalse {
            get {
                return ResourceManager.GetString("CRealAssumedValueSetFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datetime value &apos;{0}&apos; does not match pattern &apos;{1}&apos;..
        /// </summary>
        internal static string DateTimeXDoesNotMatchPatternY {
            get {
                return ResourceManager.GetString("DateTimeXDoesNotMatchPatternY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datetime value &apos;{0}&apos; is out of range..
        /// </summary>
        internal static string DateTimeXOutOfRange {
            get {
                return ResourceManager.GetString("DateTimeXOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date value &apos;{0}&apos; does not match pattern &apos;{1}&apos;..
        /// </summary>
        internal static string DateXDoesNotMatchPatternY {
            get {
                return ResourceManager.GetString("DateXDoesNotMatchPatternY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date value &apos;{0}&apos; is out of range..
        /// </summary>
        internal static string DateXOutOfRange {
            get {
                return ResourceManager.GetString("DateXOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default archetype root must be of type Locatable..
        /// </summary>
        internal static string DefaultArchetypeMustBeTypeLocatable {
            get {
                return ResourceManager.GetString("DefaultArchetypeMustBeTypeLocatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;DefaultValue&apos; property of {0} is not yet implemented..
        /// </summary>
        internal static string DefaultValueNotImplementedInX {
            get {
                return ResourceManager.GetString("DefaultValueNotImplementedInX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration value &apos;{0}&apos; does not match pattern &apos;{1}&apos;..
        /// </summary>
        internal static string DurationXDoesNotMatchPatternY {
            get {
                return ResourceManager.GetString("DurationXDoesNotMatchPatternY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration value &apos;{0}&apos; is out of range..
        /// </summary>
        internal static string DurationXOutOfRange {
            get {
                return ResourceManager.GetString("DurationXOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DvOrdinal symbol value &apos;{0}&apos; does not match  the term definition for the symbol code ({1}).
        /// </summary>
        internal static string DvOrdinalSymbolXIncorrectForCodeY {
            get {
                return ResourceManager.GetString("DvOrdinalSymbolXIncorrectForCodeY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existence.Lower must be &gt;=0 and Existence.Upper must &lt;=1..
        /// </summary>
        internal static string ExistenceOutOfRange {
            get {
                return ResourceManager.GetString("ExistenceOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting archetypeNodeId &apos;{0}&apos; but got &apos;{1}&apos;..
        /// </summary>
        internal static string ExpectingNodeIdXButGotY {
            get {
                return ResourceManager.GetString("ExpectingNodeIdXButGotY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one unnamed child present. Only one unnamed child is expected..
        /// </summary>
        internal static string ExpectingOnlyOneUnnamedChild {
            get {
                return ResourceManager.GetString("ExpectingOnlyOneUnnamedChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting value &apos;{0}&apos; to be of type {1}..
        /// </summary>
        internal static string ExpectingValueXToBeTypeY {
            get {
                return ResourceManager.GetString("ExpectingValueXToBeTypeY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression.Type must be &apos;BOOLEAN&apos;..
        /// </summary>
        internal static string ExpressionTypeNotBoolean {
            get {
                return ResourceManager.GetString("ExpressionTypeNotBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting Node ID &apos;{0}&apos; but got &apos;{1}&apos;..
        /// </summary>
        internal static string IncorrectNodeId {
            get {
                return ResourceManager.GetString("IncorrectNodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting RmType &apos;{0}&apos; but got &apos;{1}&apos;..
        /// </summary>
        internal static string IncorrectRmType {
            get {
                return ResourceManager.GetString("IncorrectRmType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer value ({0}) is out of range..
        /// </summary>
        internal static string IntegerXOutOfRange {
            get {
                return ResourceManager.GetString("IntegerXOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArchetypeInternalRef target path&apos;s final path part must start with the reference model attribute name &apos;{0}&apos; as defined by its parent..
        /// </summary>
        internal static string InternalRefTargetPathFinalPartNameIncorrect {
            get {
                return ResourceManager.GetString("InternalRefTargetPathFinalPartNameIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid DvOrdinal..
        /// </summary>
        internal static string InvalidDvOrdinalX {
            get {
                return ResourceManager.GetString("InvalidDvOrdinalX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid DvQuantity..
        /// </summary>
        internal static string InvalidDvQuantityX {
            get {
                return ResourceManager.GetString("InvalidDvQuantityX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid DvState..
        /// </summary>
        internal static string InvalidDvStateX {
            get {
                return ResourceManager.GetString("InvalidDvStateX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid integer value ({0})..
        /// </summary>
        internal static string InvalidIntegerX {
            get {
                return ResourceManager.GetString("InvalidIntegerX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid ISO8601 datetime..
        /// </summary>
        internal static string InvalidIsoDateTimeX {
            get {
                return ResourceManager.GetString("InvalidIsoDateTimeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid ISO8601 date..
        /// </summary>
        internal static string InvalidIsoDateX {
            get {
                return ResourceManager.GetString("InvalidIsoDateX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid ISO8601 duration..
        /// </summary>
        internal static string InvalidIsoDurationX {
            get {
                return ResourceManager.GetString("InvalidIsoDurationX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid ISO8601 time..
        /// </summary>
        internal static string InvalidIsoTime {
            get {
                return ResourceManager.GetString("InvalidIsoTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid real value ({0})..
        /// </summary>
        internal static string InvalidRealX {
            get {
                return ResourceManager.GetString("InvalidRealX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid string value &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidStringX {
            get {
                return ResourceManager.GetString("InvalidStringX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;IsSubsetOf&apos; method of {0} is not yet implemented..
        /// </summary>
        internal static string IsSubsetNotImplementedInX {
            get {
                return ResourceManager.GetString("IsSubsetNotImplementedInX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data item of type &apos;{0}&apos; is not allowed by attribute &apos;{2}&apos; child(ren) constraint(s)..
        /// </summary>
        internal static string ItemXNotAllowedByAttributeY {
            get {
                return ResourceManager.GetString("ItemXNotAllowedByAttributeY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data item of type &apos;{0}&apos; with node ID &apos;{1}&apos; is not allowed by attribute &apos;{2}&apos; child(ren) constraint(s)..
        /// </summary>
        internal static string ItemXWithIdYNotAllowedByAttributeZ {
            get {
                return ResourceManager.GetString("ItemXWithIdYNotAllowedByAttributeZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find any cObject(s) with nodeId &apos;{0}&apos;..
        /// </summary>
        internal static string MissingChildrenWithNodeIdX {
            get {
                return ResourceManager.GetString("MissingChildrenWithNodeIdX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected child of multiple attribute to be assignable to CComplexObject..
        /// </summary>
        internal static string MultiAttributeChildNotComplexObj {
            get {
                return ResourceManager.GetString("MultiAttributeChildNotComplexObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMultipleAttributes.Members() is not null so each member&apos;s Occurences.Upper must be &lt;=1..
        /// </summary>
        internal static string MultiAttributeMembersBad {
            get {
                return ResourceManager.GetString("MultiAttributeMembersBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected constraint object for name attribute..
        /// </summary>
        internal static string NameConstraintExpected {
            get {
                return ResourceManager.GetString("NameConstraintExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a constraint to match path: {0}..
        /// </summary>
        internal static string NoConstraintForPathX {
            get {
                return ResourceManager.GetString("NoConstraintForPathX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find a legitimate matching node at the target path &apos;{0}&apos;..
        /// </summary>
        internal static string NoNodeMatchAtPath {
            get {
                return ResourceManager.GetString("NoNodeMatchAtPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match found in attribute &apos;{0}&apos; child(ren) constraints for data item being validated. The current data item is thus not allowed..
        /// </summary>
        internal static string NotAllowedByAttributeXConstraint {
            get {
                return ResourceManager.GetString("NotAllowedByAttributeXConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not enough occurrences of node with archetype code &apos;{0}&apos;. Expecting at least {1} but got {2}..
        /// </summary>
        internal static string NotEnoughOccurrences {
            get {
                return ResourceManager.GetString("NotEnoughOccurrences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archetype ontology does not have term for archetype definition..
        /// </summary>
        internal static string OntologyMissingDefinitionTerm {
            get {
                return ResourceManager.GetString("OntologyMissingDefinitionTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archetype &apos;{0}&apos; ontology must contain language &apos;{1}&apos;..
        /// </summary>
        internal static string OntologyMustContainLanguageY {
            get {
                return ResourceManager.GetString("OntologyMustContainLanguageY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} operator cannot be used for a {1} value..
        /// </summary>
        internal static string OperatorXInvalidForTypeY {
            get {
                return ResourceManager.GetString("OperatorXInvalidForTypeY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following path is not unique for the path part where node ID is &apos;{0}&apos;: {1}..
        /// </summary>
        internal static string PathYNotUniqueAtX {
            get {
                return ResourceManager.GetString("PathYNotUniqueAtX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real value ({0}) is out of range..
        /// </summary>
        internal static string RealXOutOfRange {
            get {
                return ResourceManager.GetString("RealXOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; expected according to the reference model but is missing..
        /// </summary>
        internal static string RmExpectedConstraintMissing {
            get {
                return ResourceManager.GetString("RmExpectedConstraintMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root ArchetypeConstraint must be assignable to CComplexObject..
        /// </summary>
        internal static string RootConstraintInvalid {
            get {
                return ResourceManager.GetString("RootConstraintInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CObject.Parent is not null and is CSingleAttribute so its Occurrences.Upper must be &lt;=1..
        /// </summary>
        internal static string SingleParentOccurrencesBad {
            get {
                return ResourceManager.GetString("SingleParentOccurrencesBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot must not be full..
        /// </summary>
        internal static string SlotMustNotBeFull {
            get {
                return ResourceManager.GetString("SlotMustNotBeFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;StandardEquivalent&apos; method of {0} is not yet implemented..
        /// </summary>
        internal static string StandardEquivNotImplementedInX {
            get {
                return ResourceManager.GetString("StandardEquivNotImplementedInX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String value &apos;{0}&apos; does not match pattern &apos;{1}&apos;..
        /// </summary>
        internal static string StringXDoesNotMatchPatternY {
            get {
                return ResourceManager.GetString("StringXDoesNotMatchPatternY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DvCodedText value &apos;{0}&apos; does not match the term definition for the code_string &apos;{1}&apos;..
        /// </summary>
        internal static string TextValueXInvalidForCodeY {
            get {
                return ResourceManager.GetString("TextValueXInvalidForCodeY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time value &apos;{0}&apos; does not match pattern &apos;{1}&apos;..
        /// </summary>
        internal static string TimeXDoesNotMatchPatternY {
            get {
                return ResourceManager.GetString("TimeXDoesNotMatchPatternY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time value &apos;{0}&apos; is out of range..
        /// </summary>
        internal static string TimeXOutOfRange {
            get {
                return ResourceManager.GetString("TimeXOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; expected according to archetype/template constraint but is missing..
        /// </summary>
        internal static string TmExpectedConstraintMissing {
            get {
                return ResourceManager.GetString("TmExpectedConstraintMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; is forbidden but exists..
        /// </summary>
        internal static string TmForbiddenConstraint {
            get {
                return ResourceManager.GetString("TmForbiddenConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are too many occurrences of node with archetype code &apos;{0}&apos;. Expecting at most {1} but got {2}..
        /// </summary>
        internal static string TooManyOccurrences {
            get {
                return ResourceManager.GetString("TooManyOccurrences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; is not supported for {1} operator..
        /// </summary>
        internal static string TypeXNotSupportedByYOperator {
            get {
                return ResourceManager.GetString("TypeXNotSupportedByYOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected attribute &apos;{0}&apos; is present..
        /// </summary>
        internal static string UnexpectedAttributeX {
            get {
                return ResourceManager.GetString("UnexpectedAttributeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression operator &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string UnsupportedExpressionOperator {
            get {
                return ResourceManager.GetString("UnsupportedExpressionOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExprLeaf.ReferenceType &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string UnsupportedExprLeafReferenceType {
            get {
                return ResourceManager.GetString("UnsupportedExprLeafReferenceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value being validated must implement IRmType, but is of type {0} which does not..
        /// </summary>
        internal static string ValueMustImplementIRmType {
            get {
                return ResourceManager.GetString("ValueMustImplementIRmType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a {1} value..
        /// </summary>
        internal static string XIsNotTypeYValue {
            get {
                return ResourceManager.GetString("XIsNotTypeYValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be a valid {1}..
        /// </summary>
        internal static string XMustBeValidY {
            get {
                return ResourceManager.GetString("XMustBeValidY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of type {0} is expected to implement {1} but does not..
        /// </summary>
        internal static string XMustImplementY {
            get {
                return ResourceManager.GetString("XMustImplementY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordinal value ({0}) is not in CDvOrdinal.List..
        /// </summary>
        internal static string XNotInCDvOrdinalList {
            get {
                return ResourceManager.GetString("XNotInCDvOrdinalList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer value ({0}) is not in CInteger.List..
        /// </summary>
        internal static string XNotInCIntegerList {
            get {
                return ResourceManager.GetString("XNotInCIntegerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real value ({0}) is not in CReal.List..
        /// </summary>
        internal static string XNotInCRealList {
            get {
                return ResourceManager.GetString("XNotInCRealList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String  value ({0}) is not in CString.List..
        /// </summary>
        internal static string XNotInCStringList {
            get {
                return ResourceManager.GetString("XNotInCStringList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match found in attribute &apos;{0}&apos; child(ren) constraints for data item being validated ({1}). The current data item is thus not allowed..
        /// </summary>
        internal static string YNotAllowedByAttributeXConstraint {
            get {
                return ResourceManager.GetString("YNotAllowedByAttributeXConstraint", resourceCulture);
            }
        }
    }
}
