//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenEhr.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenEhr.Resources.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assertion expression type must be &apos;BOOLEAN&apos; where expression is not null..
        /// </summary>
        internal static string AssertionExpressMustBeBool {
            get {
                return ResourceManager.GetString("AssertionExpressMustBeBool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBoolean.DefaultValue invalid against the CBoolean restrictions..
        /// </summary>
        internal static string CBooleanDefaultInvalid {
            get {
                return ResourceManager.GetString("CBooleanDefaultInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of CBoolean.TrueValid and CBoolean.FalseValid must be true..
        /// </summary>
        internal static string CBooleanInvariant {
            get {
                return ResourceManager.GetString("CBooleanInvariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If CDuration.Range is null, pattern must not be null..
        /// </summary>
        internal static string CDurationPatternAndRangeNull {
            get {
                return ResourceManager.GetString("CDurationPatternAndRangeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If CIngeger.List or CInteger.Range is not null, the other must be null..
        /// </summary>
        internal static string CIntegerListAndRangeNotNull {
            get {
                return ResourceManager.GetString("CIntegerListAndRangeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either CInteger.List of CInteger.Range must be not null..
        /// </summary>
        internal static string CIntegerListXorRange {
            get {
                return ResourceManager.GetString("CIntegerListXorRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If CReal.List or CReal.Range is not null, the other must be null..
        /// </summary>
        internal static string CRealListAndRangeNotNull {
            get {
                return ResourceManager.GetString("CRealListAndRangeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either CReal.List of CReal.Range must be not null..
        /// </summary>
        internal static string CRealListXorRange {
            get {
                return ResourceManager.GetString("CRealListXorRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If CString.List or CString.Pattern is not null, the other must be null..
        /// </summary>
        internal static string CStringListAndPatternNotNull {
            get {
                return ResourceManager.GetString("CStringListAndPatternNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either CString.List or CString.Pattern must be not null..
        /// </summary>
        internal static string CStringListXorPattern {
            get {
                return ResourceManager.GetString("CStringListXorPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date pattern is invalid: {0}..
        /// </summary>
        internal static string DatePatternInvalid {
            get {
                return ResourceManager.GetString("DatePatternInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serialisation of default values not implemented..
        /// </summary>
        internal static string DefaultsSerialisationNotImplemented {
            get {
                return ResourceManager.GetString("DefaultsSerialisationNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration pattern is invalid: {0}..
        /// </summary>
        internal static string DurationPatternInvalid {
            get {
                return ResourceManager.GetString("DurationPatternInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either trueValid or falseValid must be set to true..
        /// </summary>
        internal static string EitherTrueOrFalseMustBeValid {
            get {
                return ResourceManager.GetString("EitherTrueOrFalseMustBeValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected local name is &apos;{0}&apos;, not &apos;{1}&apos;..
        /// </summary>
        internal static string ExpectedLocalNameIsXNotY {
            get {
                return ResourceManager.GetString("ExpectedLocalNameIsXNotY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If {0} is not null it must not be empty..
        /// </summary>
        internal static string IfXIsNotNullMustBeEmpty {
            get {
                return ResourceManager.GetString("IfXIsNotNullMustBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid DayValidity..
        /// </summary>
        internal static string InvalidDayValidityX {
            get {
                return ResourceManager.GetString("InvalidDayValidityX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid HourValidity..
        /// </summary>
        internal static string InvalidHourValidityX {
            get {
                return ResourceManager.GetString("InvalidHourValidityX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid MinuteValidity..
        /// </summary>
        internal static string InvalidMinuteValidityX {
            get {
                return ResourceManager.GetString("InvalidMinuteValidityX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid MonthValidity..
        /// </summary>
        internal static string InvalidMonthValidityX {
            get {
                return ResourceManager.GetString("InvalidMonthValidityX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is an invalid SecondValidity..
        /// </summary>
        internal static string InvalidSecondValidityX {
            get {
                return ResourceManager.GetString("InvalidSecondValidityX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method &apos;{0}&apos; with parameter type &apos;{1}&apos; is looping and is terminated..
        /// </summary>
        internal static string LoopingMethodTerminated {
            get {
                return ResourceManager.GetString("LoopingMethodTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method &apos;{0}&apos; with parameter type &apos;{1}&apos; is not implemented..
        /// </summary>
        internal static string MethodXNotImplementedForParamTypeY {
            get {
                return ResourceManager.GetString("MethodXNotImplementedForParamTypeY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archetype ontology does not contain specified term/constraint code ({0})..
        /// </summary>
        internal static string OntologyMissingCode {
            get {
                return ResourceManager.GetString("OntologyMissingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archetype ontology does not contain specified language ({0})..
        /// </summary>
        internal static string OntologyMissingLanguageX {
            get {
                return ResourceManager.GetString("OntologyMissingLanguageX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archetype ontology does not contain specified terminology ({0})..
        /// </summary>
        internal static string OntologyMissingTerminologyX {
            get {
                return ResourceManager.GetString("OntologyMissingTerminologyX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to openEHR type {0} does not have an AmTypeAttribute..
        /// </summary>
        internal static string OpenEhrTypeMissingAmTypeAttribute {
            get {
                return ResourceManager.GetString("OpenEhrTypeMissingAmTypeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date pattern must be null before being set..
        /// </summary>
        internal static string PatternMustBeNullBeforeSet {
            get {
                return ResourceManager.GetString("PatternMustBeNullBeforeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular expression match groups must not be null..
        /// </summary>
        internal static string RegexGroupsMustNotBeNull {
            get {
                return ResourceManager.GetString("RegexGroupsMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialisation depth value must be &gt;=0..
        /// </summary>
        internal static string SpecialisationDepthLessThanZero {
            get {
                return ResourceManager.GetString("SpecialisationDepthLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time pattern is invalid: {0}..
        /// </summary>
        internal static string TimePatternInvalid {
            get {
                return ResourceManager.GetString("TimePatternInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is null..
        /// </summary>
        internal static string XIsNull {
            get {
                return ResourceManager.GetString("XIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is null or empty..
        /// </summary>
        internal static string XIsNullOrEmpty {
            get {
                return ResourceManager.GetString("XIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not be null..
        /// </summary>
        internal static string XMustNotBeNull {
            get {
                return ResourceManager.GetString("XMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not be null or empty..
        /// </summary>
        internal static string XMustNotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("XMustNotBeNullOrEmpty", resourceCulture);
            }
        }
    }
}
